name: CI/CD Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolioproject:latest .

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolioproject:latest

    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/portfolioproject:latest
          docker stop portfolioproject || true
          docker rm portfolioproject || true
          docker run -d -p 80:80 --name portfolioproject ${{ secrets.DOCKER_USERNAME }}/portfolioproject:latest
